routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

Route::get('/cities/{id}', 'WelcomeController@getCities')->name('cities');

Route::post('/card', 'WelcomeController@cardInformation')->name('card.information');

Route::get('refresh-captcha', 'WelcomeController@refreshCaptcha')->name('refreshCaptcha');
Route::get('/auth-permissions', 'WelcomeController@authPremissions')->name('auth-premissions');

Route::middleware(['checkIp'])->group(function () {
    Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/login', 'Auth\LoginController@login');
    Route::post('/logout', 'Auth\LoginController@logout')->name('logout');


    Route::get('/site/account_verify/{id}', 'Auth\VerificationController@accountVerify')->name('site-account_verify');
    Route::any('/site/account_verify', 'Auth\VerificationController@accountVerification')->name('site-account_verification');


    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/no-permissions', 'HomeController@noPremissions')->name('no-premissions');
});

Route::middleware(['auth','admin','checkIp'])->prefix('admin')->group(function () {
    Route::get('users/json', 'UserController@json')->name('users.json');
    Route::resource('users', 'UserController');
    Route::get('branches/json', 'BranchController@json')->name('branches.json');
    Route::resource('branches', 'BranchController');
    Route::get('logs', 'HomeController@logsIndex')->name('logs.index');
});

Route::middleware(['auth','associate','checkIp'])->prefix('staff')->group(function () {
    Route::get('information/json', 'InfoController@json')->name('information.json');
    Route::get('information', 'InfoController@index')->name('information.index');


    Route::post('logs', 'InfoController@storeLogs')->name('logs.store');
});

app/Models/Branch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Branch extends Model
{
    //

    const ACTIVE_USER = 1;
    const INACTIVE_USER = 2;


    protected $fillable = [
        'name',  'status', 'branch_code'
    ];



    public static function getStatus()
    {
        $statuses = array(
         array('id' => self::ACTIVE_USER, 'name'=>'Active'),
         array('id' => self::INACTIVE_USER, 'name'=>'Inactive'),
          );
        return $statuses;
    }


    /**
     * Set Branch Name Attribute
     *
     * @return string
     */
    public function setNameAttribute($name)
    {
        return $this->attributes['name'] = $name;
    }

    /**
     * Get name Attribute
     */
    public function getNameAttribute($name)
    {
        return ucwords(strtolower($name));
    }

    public function Delivery()
    {
        return $this->hasMany(Branch::class, 'id', 'branch');
    }

    public function InformationBranch()
    {
        return $this->hasMany(InformationBranch::class, 'id', 'information_id');
    }
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Branch;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Str;
use Validator;
use Session;
use Redirect;
use Hash;
use Mail;
use Auth;
use DB;
use Carbon\Carbon;

class BranchController extends Controller
{
    //
    public function index(){
        return view('branches.index');
  
      }
      public function json(){
  
        $query = Branch::all();
  
       return Datatables::of($query)
       
       ->addColumn('status',function($list){
         if($list->status == 1){
         
           return 'Active';
         }else{
           return 'Inactive';
         }
  
       })
    
         ->addColumn('tools', function ($list) {
  
              return '
         <span style="overflow: visible; position: relative; width: 110px;">
  
           <a title="Edit details" class="btn btn-sm btn-clean btn-icon btn-icon-sm" href="' . route('branches.edit', $list->id) . '">
             <i class="fas fa-edit"></i>
           </a>
           <a
             title="Delete"
             class="btn btn-sm btn-clean btn-icon btn-icon-sm  delete-action"
             data-href="'.route('branches.destroy', $list->id).'"
             data-toggle="modal"
             data-target="#deleteConfirmModal"
             >
             <i class="far fa-trash-alt"></i>
           </a>
  
       </span>';
  
         })
         ->rawColumns(['tools'])
         ->make();
  
      }
  
  
    public function create(){
     
      $statuses = Branch::getStatus();
      return view('branches.create', compact('statuses'));
  
    }
  
  
    public function store(Request $request){
      $data = $request->all();
      $validator = Validator::make($data, [
          'name' => ['required', 'string', 'max:255'],
          'status' =>['required']
      ]);
   
      if ($validator->fails()) {
        $errors = $validator->errors();
        return Redirect::back()->withErrors($errors);
      }
  
  
        $branch = new Branch();
        $branch->name = $data['name'];
        $branch->status = $data['status'];
        $branch->save();
  
  
        return redirect()->route('branches.index');
  
    }
  
  
      public function edit($id){
         $branch = Branch::where('id',$id)->first();
         $statuses = Branch::getStatus();
        return view('branches.edit', compact('branch','statuses'));
   }
  
   public function update(Request $request, $id){
     $data = $request->all();
     $validator = Validator::make($data, [
      'name' => ['required', 'string', 'max:255'],
      'status' =>['required']
  ]);
  
     if ($validator->fails()) {
       $errors = $validator->errors();
       return Redirect::back()->withErrors($errors);
     }
  
     $branch = Branch::where('id',$id)->first();
     $branch->name = $data['name'];
     $branch->status = $data['status'];
  
     $branch->save();
  
      return redirect()->route('branches.index');
  
   }
  
   public function destroy(Request $request, $id){
     Branch::where('id',$id)->delete();
  
     return redirect()->route('branches.index');
  
   }

    
}

resources/views/branches/create.blade.php
@extends('layouts.admin')

@section('header')
<div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Create Branch</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
              <li class="breadcrumb-item active"><a href="{{route('branches.index')}}">Branches </a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->

@endsection

@section('content')
     <div class="container-fluid">
        <div class="row">
         <div class="col-12">
            <div class="card">
              <!-- /.card-header -->
              <div class="card-body">
               
               <form role="form" method="post" action="{{route('branches.store')}}">
                {{ csrf_field() }}
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text"  class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name')  }}" required>

                    @if ($errors->has('name'))
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $errors->first('name') }}</strong>
                    </span>
                    @endif
                  </div>
                      <div class="form-group ">
                        <label for="exampleInputEmail1">Status</label>
                            <select id="role" name="status" class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}" required>
                            <option disabled selected>Select status</option>
                            @foreach($statuses as $status)
                           
                             <option value="{{$status['id']}}">{{$status['name']}}</option>
                              
                            @endforeach
                            </select>
      
                                @if ($errors->has('status'))
                                <span class="invalid-feedback" role="alert">
                                  <strong>{{ $errors->first('status') }}</strong>
                                </span>
                                @endif
      
                          </div>
                </div>

               
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary pull-right">Submit</button>
                </div>
              </form>
              </div>
            </div>
          </div>
          
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
@endsection

resources/views/branches/edit.blade.php
@extends('layouts.admin')

@section('header')
<div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Edit: {{ $branch->first_name  }}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
              <li class="breadcrumb-item active"><a href="{{route('branches.index')}}">Users </a></li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->

@endsection

@section('content')
     <div class="container-fluid">
        <div class="row">
         <div class="col-12">
            <div class="card">
              <!-- /.card-header -->
              <div class="card-body">

               <form role="form" method="post" action="{{ route('branches.update',$branch->id) }}">
                 @method('PUT')
                 @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text"  class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $branch->name  }}" required>

                    @if ($errors->has('name'))
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $errors->first('name') }}</strong>
                    </span>
                    @endif
                  </div>
              
                          <div class="form-group ">
                            <label for="exampleInputEmail1">Status</label>
                                <select id="status" name="status" class="form-control{{ $errors->has('status') ? ' is-invalid' : '' }}" required>
                                <option disabled >Select Status</option>
                                @foreach($statuses as $status)
                                @if($status['id'] === $branch->status)
                                  <option value="{{$status['id']}}" selected="selected">{{$status['name']}}</option>
                                  @else
                                 <option value="{{$status['id']}}">{{$status['name']}}</option>
                                  @endif
                                @endforeach
                                </select>
    
                                    @if ($errors->has('status'))
                                    <span class="invalid-feedback" role="alert">
                                      <strong>{{ $errors->first('status') }}</strong>
                                    </span>
                                    @endif
    
                              </div>
                          
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
              </div>
            </div>
          </div>

        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
@endsection

resources/views/branches/index.blade.php
@extends('layouts.admin')

@section('header')
<div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Branches</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
              <li class="breadcrumb-item active">Branches </li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row mb-2">
          <div class="col-sm-11">
          </div><!-- /.col -->
          
          @if(Auth::user()->role->name ==='Administator')
          <div class="col-sm-1">
            <a href="{{route('branches.create')}}" class="btn btn-block btn-primary"> Add Branch</a>
          </div><!-- /.col -->
          @endif
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->

@endsection

@section('content')
     <div class="container-fluid">
        <div class="row">
         <div class="col-12">
            <div class="card">
              <!-- /.card-header -->
              <div class="card-body">
               <table class="table table-bordered table-striped table-hover dt-responsive" id="branches" width="100%">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Tool</th>
                  </tr>
                </thead>
              </table>
              </div>
            </div>
          </div>

        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
@endsection

@section('footer-js')
<script>
$(document).ready(function(){
  $('#branches').DataTable({
    responsive: true,
    "deferRender": true,
    "processing": true,
    "serverSide": true,
    "ordering": true, //disable column ordering
    "lengthMenu": [
      [5, 10, 15, 20, 25, -1],
      [5, 10, 15, 20, 25, "All"] // change per page values here
    ],
    "pageLength": 100,
    "ajax": {
      url: '{!! route('branches.json') !!}',
      method: 'GET'
    },
    // dom: '<"html5buttons"B>lTfgitp',
    "dom": "<'row' <'col-md-12'>><'row'<'col-md-8 col-sm-12'lB><'col-md-4 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable
    buttons: [
      { extend: 'copy',exportOptions: {columns: [0, 1, 2, 3,4,5,6]}},
      {extend: 'csv',  title: '{{ config('app.name', 'DTB') }} - List of Bank Branches',exportOptions: {columns: [0, 1, 2]}},
      {extend: 'excel', title: '{{ config('app.name', 'DTB') }} - List of Bank Branches',exportOptions: {columns: [0, 1, 2]}},
      {extend: 'pdf', title: '{{ config('app.name', 'DTB') }} - List of Bank Branches',exportOptions: {columns: [0, 1, 2]}},
      {extend: 'print',
      customize: function (win){
        $(win.document.body).addClass('white-bg');
        $(win.document.body).css('font-size', '10px');
        $(win.document.body).find('table')
        .addClass('compact')
        .css('font-size', 'inherit');
      }
    }
  ],
  columns: [
    {data: 'id',render: function (data, type, row, meta) {
        return meta.row + meta.settings._iDisplayStart + 1;
      }},
    {data: 'name', name: 'name', orderable: true, searchable: true},
    {data: 'status', name: 'status', orderable: true, searchable: true},
    {data: 'tools', name: 'tools', orderable: false, searchable: false,"defaultContent": "<i>Not set</i>"},
  ],
});
});

</script>

@endsection